local function groups(p)
  return {
    Normal = { fg = p.fg, bg = p.bg },
    NormalNC = { fg = p.fg, bg = p.bg },
    NormalFloat = { fg = p.fg, bg = p.bg_subtle },
    FloatBorder = { fg = p.border, bg = p.bg_subtle },
    WinSeparator = { fg = p.border, bg = p.bg },
    CursorLine = { bg = p.bg_alt },
    CursorColumn = { bg = p.bg_alt },
    ColorColumn = { bg = p.bg_alt },
    LineNr = { fg = p.line_nr, bg = p.bg },
    CursorLineNr = { fg = p.line_nr_active, bg = p.bg },
    SignColumn = { fg = p.line_nr, bg = p.bg },
    Folded = { fg = p.fg_muted, bg = p.bg_alt },
    FoldColumn = { fg = p.line_nr, bg = p.bg },
    VertSplit = { fg = p.border, bg = p.bg },
    StatusLine = { fg = p.fg, bg = p.bg_alt },
    StatusLineNC = { fg = p.fg_muted, bg = p.bg_alt },
    TabLine = { fg = p.fg_muted, bg = p.bg_alt },
    TabLineSel = { fg = p.fg, bg = p.bg_active },
    TabLineFill = { fg = p.bg_alt, bg = p.bg_alt },
    Pmenu = { fg = p.fg, bg = p.bg_alt },
    PmenuSel = { fg = p.fg, bg = p.bg_hover },
    PmenuSbar = { bg = p.bg_alt },
    PmenuThumb = { bg = p.fg_dim },
    Visual = { bg = p.bg_hover },
    Search = { fg = p.fg, bg = p.search },
    IncSearch = { fg = p.bg, bg = p.accent },
    CurSearch = { fg = p.bg, bg = p.accent },
    MatchParen = { fg = p.accent, bg = p.bg_active },
    Title = { fg = p.orange },
    Directory = { fg = p.accent },
    NonText = { fg = p.fg_dim },
    SpecialKey = { fg = p.fg_dim },
    Whitespace = { fg = p.bg_active },
    EndOfBuffer = { fg = p.bg },

    Comment = { fg = p.comment, italic = true },
    Constant = { fg = p.orange },
    String = { fg = p.string },
    Character = { fg = p.string },
    Number = { fg = p.orange },
    Boolean = { fg = p.orange },
    Float = { fg = p.orange },
    Identifier = { fg = p.fg },
    Function = { fg = p.orange },
    Statement = { fg = p.line_nr },
    Conditional = { fg = p.line_nr },
    Repeat = { fg = p.line_nr },
    Label = { fg = p.orange },
    Operator = { fg = p.line_nr },
    Keyword = { fg = p.line_nr },
    Exception = { fg = p.line_nr },
    PreProc = { fg = p.orange },
    Include = { fg = p.line_nr },
    Define = { fg = p.line_nr },
    Macro = { fg = p.orange },
    Type = { fg = p.orange },
    StorageClass = { fg = p.line_nr },
    Structure = { fg = p.orange },
    Typedef = { fg = p.orange },
    Special = { fg = p.orange },
    SpecialChar = { fg = p.orange },
    Tag = { fg = p.orange },
    Delimiter = { fg = p.line_nr },
    SpecialComment = { fg = p.comment, italic = true },
    Debug = { fg = p.red },

    ErrorMsg = { fg = p.red },
    WarningMsg = { fg = p.yellow },

    DiffAdd = { fg = p.green, bg = p.hint_bg },
    DiffChange = { fg = p.yellow, bg = p.warning_bg },
    DiffDelete = { fg = p.red, bg = p.error_bg },
    DiffText = { fg = p.blue, bg = p.info_bg },

    GitSignsAdd = { fg = p.green },
    GitSignsChange = { fg = p.yellow },
    GitSignsDelete = { fg = p.red },

    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.yellow },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.cyan },
    DiagnosticOk = { fg = p.green },
    DiagnosticVirtualTextError = { fg = p.red, bg = p.error_bg },
    DiagnosticVirtualTextWarn = { fg = p.yellow, bg = p.warning_bg },
    DiagnosticVirtualTextInfo = { fg = p.blue, bg = p.info_bg },
    DiagnosticVirtualTextHint = { fg = p.cyan, bg = p.hint_bg },
    DiagnosticUnderlineError = { undercurl = true, sp = p.red },
    DiagnosticUnderlineWarn = { undercurl = true, sp = p.yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = p.blue },
    DiagnosticUnderlineHint = { undercurl = true, sp = p.cyan },

    LspReferenceText = { bg = p.bg_active },
    LspReferenceRead = { bg = p.bg_active },
    LspReferenceWrite = { bg = p.bg_active },

    SpellBad = { undercurl = true, sp = p.red },
    SpellCap = { undercurl = true, sp = p.yellow },
    SpellLocal = { undercurl = true, sp = p.blue },
    SpellRare = { undercurl = true, sp = p.magenta },

    TreesitterContext = { bg = p.bg_alt },
    TreesitterContextLineNumber = { fg = p.line_nr_active, bg = p.bg_alt },

    TelescopeNormal = { fg = p.fg, bg = p.bg_subtle },
    TelescopeBorder = { fg = p.border, bg = p.bg_subtle },
    TelescopePromptBorder = { fg = p.border, bg = p.bg_subtle },
    TelescopeResultsBorder = { fg = p.border, bg = p.bg_subtle },
    TelescopePreviewBorder = { fg = p.border, bg = p.bg_subtle },
    TelescopePromptNormal = { fg = p.fg, bg = p.bg_subtle },
    TelescopeResultsNormal = { fg = p.fg, bg = p.bg_subtle },
    TelescopePreviewNormal = { fg = p.fg, bg = p.bg_subtle },
    TelescopePromptTitle = { fg = p.fg, bg = p.bg_active },
    TelescopeResultsTitle = { fg = p.fg, bg = p.bg_active },
    TelescopePreviewTitle = { fg = p.fg, bg = p.bg_active },
    TelescopeSelection = { fg = p.fg, bg = p.bg_hover },
    TelescopeSelectionCaret = { fg = p.orange, bg = p.bg_hover },
    TelescopeMatching = { fg = p.accent },

    ["@comment"] = { fg = p.comment, italic = true },
    ["@comment.documentation"] = { fg = p.comment, italic = true },
    ["@constant"] = { fg = p.orange },
    ["@constant.builtin"] = { fg = p.orange },
    ["@constant.macro"] = { fg = p.orange },
    ["@string"] = { fg = p.string },
    ["@string.escape"] = { fg = p.orange },
    ["@string.regex"] = { fg = p.string },
    ["@string.special"] = { fg = p.string },
    ["@character"] = { fg = p.string },
    ["@number"] = { fg = p.orange },
    ["@boolean"] = { fg = p.orange },
    ["@float"] = { fg = p.orange },
    ["@variable"] = { fg = p.fg },
    ["@variable.builtin"] = { fg = p.line_nr },
    ["@variable.parameter"] = { fg = p.fg },
    ["@variable.member"] = { fg = p.fg },
    ["@function"] = { fg = p.orange },
    ["@function.builtin"] = { fg = p.orange },
    ["@function.call"] = { fg = p.orange },
    ["@method"] = { fg = p.orange },
    ["@method.call"] = { fg = p.orange },
    ["@constructor"] = { fg = p.orange },
    ["@keyword"] = { fg = p.line_nr },
    ["@keyword.return"] = { fg = p.line_nr },
    ["@keyword.operator"] = { fg = p.line_nr },
    ["@keyword.function"] = { fg = p.line_nr },
    ["@keyword.import"] = { fg = p.line_nr },
    ["@conditional"] = { fg = p.line_nr },
    ["@repeat"] = { fg = p.line_nr },
    ["@label"] = { fg = p.orange },
    ["@operator"] = { fg = p.line_nr },
    ["@type"] = { fg = p.orange },
    ["@type.builtin"] = { fg = p.orange },
    ["@type.definition"] = { fg = p.orange },
    ["@type.qualifier"] = { fg = p.line_nr },
    ["@attribute"] = { fg = p.line_nr },
    ["@property"] = { fg = p.fg },
    ["@punctuation.delimiter"] = { fg = p.line_nr },
    ["@punctuation.bracket"] = { fg = p.line_nr },
    ["@punctuation.special"] = { fg = p.line_nr },
    ["@tag"] = { fg = p.orange },
    ["@tag.attribute"] = { fg = p.line_nr },
    ["@tag.delimiter"] = { fg = p.line_nr },
    ["@text"] = { fg = p.fg },
    ["@text.literal"] = { fg = p.string },
    ["@text.reference"] = { fg = p.accent },
    ["@text.title"] = { fg = p.orange },
    ["@text.uri"] = { fg = p.accent, underline = true },
    ["@text.emphasis"] = { fg = p.fg, italic = true },
    ["@text.strong"] = { fg = p.fg, bold = true },

    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.interface"] = { link = "Type" },
    ["@lsp.type.struct"] = { link = "Type" },
    ["@lsp.type.typeParameter"] = { link = "Type" },
    ["@lsp.type.parameter"] = { link = "Identifier" },
    ["@lsp.type.property"] = { link = "Identifier" },
    ["@lsp.type.variable"] = { link = "Identifier" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.keyword"] = { link = "Keyword" },
    ["@lsp.type.namespace"] = { link = "Identifier" },
    ["@lsp.type.macro"] = { link = "Macro" },
    ["@lsp.type.comment"] = { link = "Comment" },
    ["@lsp.type.string"] = { link = "String" },
    ["@lsp.type.number"] = { link = "Number" },
    ["@lsp.type.boolean"] = { link = "Boolean" },
  }
end

return groups
